services:
  redmine-app:
    image: redmine:6.1
    restart: always
    ports:
      - ${REDMINE_PORT}:3000
    environment:
      REDMINE_DB_POSTGRES: ${REDMINE_DB_POSTGRES}
      REDMINE_DB_DATABASE: ${REDMINE_DB_DATABASE}
      REDMINE_DB_USERNAME: ${REDMINE_DB_USERNAME}
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_SECRET_KEY_BASE: ${REDMINE_SECRET_KEY_BASE}
    volumes:
      - ./files:/usr/src/redmine/files
      - ./themes:/usr/src/redmine/themes
      - ./plugins:/usr/src/redmine/plugins
    depends_on:
      - redmine-db

  redmine-db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
